### ISSUE TITLE
analyzer: `compile_globs` is defined twice in `crates/analyzer/src/lib.rs` — the analyzer crate does not compile

### ISSUE THREAD

**Issue by unrealtim-tech** [SorobanGuard/Guard-CLI#495]
**Labels:** bug, analyzer-crate
**Crate:** analyzer

**Description**
`crates/analyzer/src/lib.rs` defines `fn compile_globs(patterns: &[String])` **twice** — once around line ~195 and again, byte-for-byte, around line ~222:

```rust
/// Compile a list of glob source strings ...
fn compile_globs(patterns: &[String]) -> Result<Vec<glob::Pattern>, ScanError> { ... }   // ~195

/// Compile glob source strings into patterns ...
fn compile_globs(patterns: &[String]) -> Result<Vec<glob::Pattern>, ScanError> { ... }   // ~222
```

This is `error[E0428]: the name 'compile_globs' is defined multiple times`. The `soroban-guard-analyzer` crate — and therefore `soroban-guard-cli` — does not compile. Looks like a bad merge that duplicated the #427 helper. Related: the two copies come with two matcher helpers (`glob_matches` ~213, `glob_hit` ~248) that are also identical — see the companion cleanup issue.

**Acceptance Criteria**
- [ ] Keep exactly one `compile_globs` and delete the duplicate.
- [ ] `cargo build -p soroban-guard-analyzer` succeeds.
- [ ] `cargo build --workspace` is not blocked by this file.

**Difficulty:** beginner

**Comment by Demilade10** [comment]
@Demilade10 has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi I can fix this


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/5b36a8af-e110-4be1-a89e-22b2af456742) or assign @Demilade10 to this issue.

**Comment by Jesutho** [comment]
@Jesutho has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> hello maintainer i will like to work on this issue as a contributor
> 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/5b36a8af-e110-4be1-a89e-22b2af456742) or assign @Jesutho to this issue.

**Comment by Miraclechukwuemeka** [comment]
@Miraclechukwuemeka has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> Hi maintainer I would like to work on this issue thank you 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/5b36a8af-e110-4be1-a89e-22b2af456742) or assign @Miraclechukwuemeka to this issue.

**Comment by martinzhames** [comment]
@martinzhames has applied to work on this issue as part of the **Stellar Wave Program**'s 8th wave.



> hi maintainer can i please work on this issue


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/5b36a8af-e110-4be1-a89e-22b2af456742) or assign @martinzhames to this issue.
